
#tiff(file=filename,width = 900, heigh=800)
meta_plot <- function(m){
forest(m,
       xlim = c(0.6,1.4),
       colgap.forest.left = unit(10,"mm"),
       colgap.forest.right = unit(10,"mm"),
       leftcols =c('studlab','n.e','n.c'),
       leftlabs=c(paste0(sexHormone_name[i]," in ",sex_name[n],",\nAuthor, Publish Year"),'Events','Total'),
       rightcols = c( "effect", "ci", "w.fixed", "w.random"),
       rightlabs = c( "RR", "[95%CI]","Weight.F","Weight.R"),
       label.right =paste0(sexHormone_name[i], " Adverse"),
       label.left  = paste0(sexHormone_name[i], " Favorable"),
       #xlab= paste0("Relative Risk (95%CI) for ",Disease[x]),
       xlab= "Relative Risk (95%CI)",
       #sortvar = adjust_num,
       sortvar = year,
       type.random='diamond',
       weight.study='random',
       type.subgroup='diamond',
       type.subgroup.random='square',
       col.by='black',
       col.inside.random='white',
       col.square='dark blue',
       col.inside='white',
       col.label.left='dark green',
       col.label.right='dark red',
       col.diamond='light blue',
       hetstat=T,
       overall.hetstat=T,
       resid.hetstat=F,
       text.subgroup.nohet=F,
       test.subgroup=F,
       ff.random='bold',
       ff.lr="bold",
       ff.xlab = 'bold',
       spacing=1.2,
       addrow.subgroups=T,
       addrow.overall=T,
       bottom.lr=F,
       fontsize=12,
       print.tau2=T,
       just="center",
       overall = T)
}

meta_plot_women <- function(m,a,b,c,d){
        forest(m,
               xlim = c(a,b),
               colgap.forest.left = unit(c,"mm"),
               colgap.forest.right = unit(d,"mm"),
               leftcols =c('studlab','n.e','n.c'),
               leftlabs=c(paste0(sexHormone_name[i]," in ",sex_name[n],",\nAuthor, Publish Year"),'Events','Total'),
               rightcols = c( "effect", "ci", "w.fixed", "w.random"),
               rightlabs = c( "RR", "[95%CI]","Weight.F","Weight.R"),
               label.right =paste0(sexHormone_name[i], " Adverse"),
               label.left  = paste0(sexHormone_name[i], " Favorable"),
               #xlab= paste0("Relative Risk (95%CI) for ",Disease[x]),
               xlab= "Relative Risk (95%CI)",
               #sortvar = adjust_num,
               sortvar = year,
               type.random='diamond',
               weight.study='random',
               type.subgroup='diamond',
               type.subgroup.random='square',
               col.by='black',
               col.inside.random='white',
               col.square='dark blue',
               col.inside='white',
               col.label.left='dark green',
               col.label.right='dark red',
               col.diamond='light blue',
               hetstat=T,
               overall.hetstat=T,
               resid.hetstat=F,
               text.subgroup.nohet=F,
               test.subgroup=F,
               ff.random='bold',
               ff.lr="bold",
               ff.xlab = 'bold',
               spacing=1.2,
               addrow.subgroups=T,
               addrow.overall=T,
               bottom.lr=F,
               fontsize=12,
               print.tau2=T,
               just="center",
               overall = T)
}



a = 0.4
b=2.5
c=15
d=10
meta_plot_g <- function(m,a,b,c,d){
        forest(m,
               xlim = c(a,b),
               colgap.forest.left = unit(c,"mm"),
               colgap.forest.right = unit(d,"mm"),
               leftcols =c('studlab','n.e','n.c'),
               leftlabs=c(paste0(sexHormone_name[i]," in ",sex_name[n],",\nAuthor, Publish Year"),'Events','Total'),
               rightcols = c( "effect", "ci", "w.fixed", "w.random"),
               rightlabs = c( "RR", "[95%CI]","Weight.F","Weight.R"),
               label.right =paste0(sexHormone_name[i], " Adverse"),
               label.left  = paste0(sexHormone_name[i], " Favorable"),
               #xlab= paste0("Relative Risk (95%CI) for ",Disease[x]),
               xlab= "Relative Risk (95%CI)",
               #sortvar = adjust_num,
               sortvar = year,
               type.random='diamond',
               weight.study='random',
               type.subgroup='diamond',
               type.subgroup.random='square',
               col.by='black',
               col.inside.random='white',
               col.square='dark blue',
               col.inside='white',
               col.label.left='dark green',
               col.label.right='dark red',
               col.diamond='light blue',
               hetstat=T,
               overall.hetstat=T,
               resid.hetstat=F,
               text.subgroup.nohet=F,
               test.subgroup=F,
               ff.random='bold',
               ff.lr="bold",
               ff.xlab = 'bold',
               spacing=1.2,
               addrow.subgroups=T,
               addrow.overall=F,
               bottom.lr=F,
               fontsize=12,
               print.tau2=T,
               just="center",
               overall = T)
}

       
meta_plot_1 <- function(m){
        forest(m,
               xlim = c(0.2,2.5),
               colgap.forest.left = unit(20,"mm"),
               colgap.forest.right = unit(10,"mm"),
               leftcols =c('studlab','n.e','n.c'),
               leftlabs=c(paste0(sexHormone_name[i]," in ",sex_name[n],",\nAuthor, Publish Year"),'Events','Total'),
               rightcols = c( "effect", "ci", "w.fixed", "w.random"),
               rightlabs = c( "RR", "[95%CI]","Weight.F","Weight.R"),
               label.right =paste0(sexHormone_name[i], " Adverse"),
               label.left  = paste0(sexHormone_name[i], " Favorable"),
               xlab= paste0("Relative Risk (95%CI) for ",Disease[x]),
               #sortvar = adjust_num,
               #sortvar = year,
               type.random='diamond',
               weight.study='random',
               type.subgroup='diamond',
               type.subgroup.random='square',
               col.by='black',
               col.inside.random='white',
               col.square='dark blue',
               col.inside='white',
               col.label.left='dark green',
               col.label.right='dark red',
               col.diamond='light blue',
               hetstat=T,
               overall.hetstat=F,
               resid.hetstat=F,
               text.subgroup.nohet=F,
               test.subgroup=F,
               ff.random='bold',
               ff.lr="bold",
               ff.xlab = 'bold',
               spacing=1.2,
               addrow.subgroups=F,
               addrow.overall=T,
               bottom.lr=F,
               fontsize=14,
               print.tau2=T,
               just="center",
               overall = T)
}
